spring:
  liquibase:
    enabled: true

  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  h2:
    console.enabled: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${PROPERTIES_MAIL_SMTP_AUTH}
          starttls:
            enable: ${PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}



security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
